image: docker:git
services:
    - docker:dind

stages:
    - build
    - push-latest

variables:
    DOCKER_IMAGE:        registry.jojoc4.ch/p2-java:${CI_BUILD_REF_NAME} #private registry where the containers will be stored
    DOCKER_LATEST_IMAGE: registry.jojoc4.ch/p2-java:latest

build:
    stage: build
    tags:
        - ubuntu-docker
    script:
        - docker build -t ${DOCKER_IMAGE} . #build the image, copy the code, compile and create jars
        - docker push ${DOCKER_IMAGE} #push the image on the registry
        - mkdir a
        - docker run --mount type=bind,source="$(pwd)"/a,target=/usr/jarf ${DOCKER_IMAGE} cp -r /usr/jar/ /usr/jarf #copy jar in artifact directory
    artifacts:
        paths:
        - a/jar/alpc.jar #save jars on gitlab server
        - a/jar/alrp.jar
        expire_in: 1 week

# if commit on branch master, push the container on registry with latest tag
push-latest:
    stage: push-latest
    tags:
        - ubuntu-docker
    script:
        - docker pull ${DOCKER_IMAGE}
        - docker tag ${DOCKER_IMAGE} ${DOCKER_LATEST_IMAGE}
        - docker push ${DOCKER_LATEST_IMAGE}
    only:
        - master
