package ch.hearc.gui.configurator;

import ch.hearc.Config;

/**
 *
 * @author jonatan.baumgart
 */
public class JPanelConfigurator extends javax.swing.JPanel {

    /**
     * Creates new form JPanelConfigurator
     */
    public JPanelConfigurator() {
        initComponents();
        Config config = Config.getConfig();
        haut.setValue(config.getNbLed(Config.NORTH));
        droite.setValue(config.getNbLed(Config.EAST));
        bas.setValue(config.getNbLed(Config.SOUTH));
        gauche.setValue(config.getNbLed(Config.WEST));
        lumMax.setValue((int) ((double) config.getLumMax() * (double) (100.0 / 255.0)));
        ip.setText(config.getRaspIp());

        //TODO verify ip input
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        haut = new javax.swing.JSpinner();
        droite = new javax.swing.JSpinner();
        bas = new javax.swing.JSpinner();
        gauche = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        lumMax = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        ip = new javax.swing.JTextField();
        btn_save = new javax.swing.JButton();

        setName(""); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre de LEDs:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel2.setText("-Haut");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 34, -1, -1));

        jLabel3.setText("-Droite");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel4.setText("-Bas");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 86, -1, -1));

        jLabel5.setText("-Gauche");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 112, -1, -1));

        haut.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));
        haut.setName(""); // NOI18N
        add(haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 31, -1, -1));

        droite.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));
        add(droite, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 57, -1, -1));

        bas.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));
        add(bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 83, -1, -1));

        gauche.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));
        add(gauche, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 109, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 135, 148, 10));

        jLabel6.setText("Luminosité Max:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 154, -1, -1));

        lumMax.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        add(lumMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 151, -1, -1));

        jLabel7.setText("%");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 154, -1, -1));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 177, 148, 10));

        jLabel8.setText("Addresse IP du raspberry pi");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 193, 148, -1));

        ip.setText("jTextField1");
        add(ip, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 213, 148, -1));

        btn_save.setText("Sauvegarder");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 239, 148, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        Config config = Config.getConfig();
        
        config.setNbLed((int)haut.getValue(), Config.NORTH);
        config.setNbLed((int)droite.getValue(), Config.EAST);
        config.setNbLed((int)bas.getValue(), Config.SOUTH);
        config.setNbLed((int)gauche.getValue(), Config.WEST);
        
        config.setLumMax((int)((int)lumMax.getValue()*(255.0/100.0)));
        
        config.setRaspIp(ip.getText());
        
        Config.save();
    }//GEN-LAST:event_btn_saveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner bas;
    private javax.swing.JButton btn_save;
    private javax.swing.JSpinner droite;
    private javax.swing.JSpinner gauche;
    private javax.swing.JSpinner haut;
    private javax.swing.JTextField ip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner lumMax;
    // End of variables declaration//GEN-END:variables
}
